name:                stafford
version:             0.1.0
github:              "albertprz/stafford"
license:             BSD3
author:              "Alberto Perez"
maintainer:          "albertoperez1994@gmail.com"
copyright:           "2023 Alberto Perez"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Minimalistic chess engine in Haskell
category:            Chess Engine

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/albertprz/stafford#readme>

dependencies:
- base >= 4 && < 5
- bookhound
- classy-prelude
- mtl
- text
- vector
- containers
- unordered-containers
- derive-storable
- timeit
- random
- QuickCheck
- newtype
- errors
- split
- composition

language: GHC2021

default-extensions:
# Prelude
- NoImplicitPrelude

# Evaluation
- StrictData

# Syntax
- LambdaCase
- MultiWayIf
- BlockArguments
- PostfixOperators

# Records
- DuplicateRecordFields
- NoFieldSelectors
- RecordWildCards
- OverloadedRecordDot

# Convenience
- OverloadedStrings

# Patterns
- ViewPatterns
- PatternSynonyms

# Implicits
- ImplicitParams


ghc-options:
- -O2
# - -fllvm
# - -funbox-strict-fields
# - -fspecialize-aggressively
# - -fexpose-all-unfoldings
# - -funfolding-use-threshold=200
# - -fspec-constr-count=20
# - -flate-dmd-anal
# - -flate-specialise

- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

# - -fprof-late
# - -finfo-table-map
# - -fdistinct-constructor-tables

# - -ddump-simpl
# - -ddump-to-file
# - -dsuppress-all
# - -dsuppress-uniques

library:
  source-dirs: src

tests:
  test:
    build-tools: hspec-discover
    source-dirs: test
    main: Spec.hs
    dependencies:
    - hspec
    - stafford
    ghc-options:
    - -Wno-type-defaults

executables:
  stafford:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

    dependencies:
    - stafford
